import re
from pathlib import Path
path = Path('src/components/Sidebar.jsx')
text = path.read_text(encoding='utf-8')
pattern = r'    children: \[(?:\r?\n(?: {6}.*| {4}\{ id: \"plants-settings\".*))+?\r?\n    \],'
replacement = '''    children: [\r\n      { id: "plants-list", path: "/plants", label: "РЎРїРёСЃРѕРє СЂР°СЃС‚РµРЅРёР№" },\r\n      {\r\n        id: "plants-pests",\r\n        path: "/pests",\r\n        label: "Р’СЂРµРґРёС‚РµР»Рё",\r\n        icon: (\r\n          <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">\r\n            <circle cx="12" cy="12" r="3" />\r\n            <path d="M12 2v4" />\r\n            <path d="M12 18v4" />\r\n            <path d="m4.93 4.93 2.83 2.83" />\r\n            <path d="m16.24 16.24 2.83 2.83" />\r\n            <path d="M2 12h4" />\r\n            <path d="M18 12h4" />\r\n            <path d="m4.93 19.07 2.83-2.83" />\r\n            <path d="m16.24 7.76 2.83-2.83" />\r\n          </svg>\r\n        ),\r\n      },\r\n      {\r\n        id: "plants-diseases",\r\n        path: "/diseases",\r\n        label: "Р—Р°Р±РѕР»РµРІР°РЅРёСЏ",\r\n        icon: (\r\n          <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">\r\n            <path d="M21 12a9 9 0 1 1-9-9" />\r\n            <path d="m22 2-5 5" />\r\n            <path d="M14 8h.01" />\r\n            <path d="M9 13h.01" />\r\n            <path d="M13 16h.01" />\r\n          </svg>\r\n        ),\r\n      },\r\n      {\r\n        id: "plants-medicines",\r\n        path: "/medicines",\r\n        label: "Р›РµРєР°СЂСЃС‚РІР°",\r\n        icon: (\r\n          <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">\r\n            <rect x="3" y="3" width="7" height="18" rx="3.5" />\r\n            <rect x="14" y="3" width="7" height="18" rx="3.5" />\r\n            <path d="M7 8h9" />\r\n          </svg>\r\n        ),\r\n      },\r\n      { id: "plants-settings", path: "/plants/settings", label: "РќР°СЃС‚СЂРѕР№РєРё", perm: "plants_admin" },\r\n    ],'''
new_text, count = re.subn(pattern, replacement, text, count=1, flags=re.DOTALL)
if count != 1:
    raise SystemExit('replacement failed')
path.write_text(new_text, encoding='utf-8')
